// The values live in GlassMetadataReferences; these names are re-exported for existing importers.
export {
    AMC_PRODUCT_REGISTER_PROGRAM_ID,
    AMC_RAW_PRODUCT_CONSUMPTION_STAGE_ID,
    AMC_RAW_SUBSTANCE_CONSUMPTION_CALCULATED_STAGE_ID,
    AMC_RAW_SUBSTANCE_CONSUMPTION_PROGRAM_ID,
    AMC_RAW_SUBSTANCE_CONSUMPTION_DATA_PROGRAM_STAGE_ID,
    AMC_CALCULATED_CONSUMPTION_DATA_PROGRAM_ID,
    AMC_CALCULATED_CONSUMPTION_DATA_PROGRAM_STAGE_ID,
    AMR_GLASS_AMC_TEA_PRODUCT_ID,
    AMR_GLASS_AMC_TEA_ATC,
    AMR_GLASS_AMC_TEA_COMBINATION,
    AMR_GLASS_AMC_TEA_ROUTE_ADMIN,
    AMR_GLASS_AMC_TEA_SALT,
    AMR_GLASS_AMC_TEA_MANUFACTURER_COUNTRY,
    AMC_MODULE_ID,
} from "../../GlassMetadataReferences";
