import { UseCase } from "../UseCase";
import { glassColors } from "../entities/GlassColors";
import { Future, FutureData } from "../entities/Future";
import { GlassModule } from "../entities/GlassModule";
import { GlassModuleRepository } from "../repositories/GlassModuleRepository";
import { AMC_MODULE_ID, AMR_MODULE_ID, EGASP_MODULE_ID } from "../entities/GlassMetadataReferences";

export class ValidateGlassModulesUseCase implements UseCase {
    constructor(private glassModuleRepository: GlassModuleRepository) {}

    public execute(): FutureData<void> {
        return this.glassModuleRepository
            .getAll()
            .flatMap(data =>
                data.length === 0 ? this.glassModuleRepository.save(glassModules) : Future.success(undefined)
            );
    }
}

const glassModules: GlassModule[] = [
    {
        id: AMR_MODULE_ID,
        name: "AMR",
        color: glassColors.lightSecondary,
        userGroups: {
            readAccess: [],
            captureAccess: [],
            approveAccess: [],
            confidentialAccess: [],
        },
        questionnaires: [],
        questionnairesType: "Dataset",
        consistencyChecks: {
            specimenPathogen: {
                ANORECTAL: [
                    {
                        NEIGON: ["J01GB", "J01DD", "J01FA", "J01XX", "J01MA", "GEN", "CRO", "CFM", "AZM", "SPT", "CIP"],
                    },
                ],
                BLOOD: [
                    {
                        ACISPP: [
                            "J01AA",
                            "J01GB",
                            "J01DH",
                            "J01XB",
                            "TGC",
                            "GEN",
                            "IPM",
                            "COL",
                            "MNO",
                            "AMK",
                            "MEM",
                            "DOR",
                        ],
                    },
                    {
                        ESCCOL: [
                            "J01EE",
                            "J01MA",
                            "J01DD",
                            "J01DE",
                            "J01DH",
                            "J01XB",
                            "J01XE",
                            "SXT",
                            "CIP",
                            "LVX",
                            "CRO",
                            "CTX",
                            "CAZ",
                            "FEP",
                            "IPM",
                            "MEM",
                            "ETP",
                            "DOR",
                            "COL",
                        ],
                    },
                    {
                        KLEPNE: [
                            "J01EE",
                            "J01MA",
                            "J01DD",
                            "J01DE",
                            "J01DH",
                            "J01XB",
                            "SXT",
                            "CIP",
                            "LVX",
                            "CRO",
                            "CTX",
                            "CAZ",
                            "FEP",
                            "IPM",
                            "MEM",
                            "ETP",
                            "DOR",
                            "COL",
                        ],
                    },
                    {
                        PSEAER: [
                            "J01DD",
                            "J01CR",
                            "J01GB",
                            "J01DH",
                            "J01XB",
                            "CAZ",
                            "TZP",
                            "GEN",
                            "AMK",
                            "TOB",
                            "IPM",
                            "MEM",
                            "DOR",
                            "COL",
                        ],
                    },
                    {
                        STAAUR: ["J01CF", "J01DC", "OXA", "FOX"],
                    },
                    {
                        STRPNE: ["J01CE", "J01CF", "J01DD", "J01EE", "J01FA", "PEN", "OXA", "CRO", "CTX", "SXT", "ERY"],
                    },
                    {
                        SALSPP: [
                            "J01MA",
                            "J01DD",
                            "J01DH",
                            "CIP",
                            "LVX",
                            "CRO",
                            "CTX",
                            "CAZ",
                            "IPM",
                            "MEM",
                            "ETP",
                            "DOR",
                        ],
                    },
                    {
                        SALTYP: [
                            "J01BA",
                            "J01CA",
                            "J01EE",
                            "J01MA",
                            "J01DD",
                            "J01FA",
                            "CHL",
                            "AMP",
                            "SXT",
                            "CIP",
                            "LVX",
                            "CRO",
                            "CTX",
                            "CAZ",
                            "AZM",
                        ],
                    },
                    {
                        SALPAR: [
                            "J01BA",
                            "J01CA",
                            "J01EE",
                            "J01MA",
                            "J01DD",
                            "J01FA",
                            "CHL",
                            "AMP",
                            "SXT",
                            "CIP",
                            "LVX",
                            "CRO",
                            "CTX",
                            "CAZ",
                            "AZM",
                        ],
                    },
                ],
                CSF: [
                    {
                        STRPNE: ["J01CE", "J01CF", "J01DD", "J01EE", "PEN", "OXA", "CRO", "CTX", "SXT"],
                    },
                    {
                        NEIMEN: ["J01CE", "J04AB", "J01MA", "J01DD", "PEN", "RIF", "CIP", "CRO", "CTX"],
                    },
                    {
                        HAEINF: ["J01CA", "J01CR", "J01DD", "J01EE", "AMP", "AMC", "CRO", "CTX", "SXT"],
                    },
                ],
                LOWRESP: [
                    {
                        STRPNE: ["J01CE", "J01DD", "J01EE", "PEN", "OXA", "CRO", "CTX", "SXT"],
                    },
                    {
                        HAEINF: [
                            "J01CA",
                            "J01CR",
                            "J01DD",
                            "J01MA",
                            "J01EE",
                            "AMP",
                            "AMC",
                            "CRO",
                            "CTX",
                            "CIP",
                            "LVX",
                            "SXT",
                        ],
                    },
                    {
                        STAAUR: ["J01CF", "J01DC", "OXA", "FOX"],
                    },
                    {
                        ACISPP: [
                            "J01AA",
                            "J01GB",
                            "J01DH",
                            "J01XB",
                            "TGC",
                            "MNO",
                            "GEN",
                            "AMK",
                            "IPM",
                            "MEM",
                            "DOR",
                            "COL",
                        ],
                    },
                    {
                        ESCCOL: [
                            "J01EE",
                            "J01MA",
                            "J01DD",
                            "J01DE",
                            "J01DH",
                            "J01XB",
                            "SXT",
                            "CIP",
                            "LVX",
                            "CRO",
                            "CTX",
                            "CAZ",
                            "FEP",
                            "IPM",
                            "MEM",
                            "ETP",
                            "DOR",
                            "COL",
                        ],
                    },
                    {
                        KLEPNE: [
                            "J01EE",
                            "J01MA",
                            "J01DD",
                            "J01DE",
                            "J01DH",
                            "J01XB",
                            "SXT",
                            "CIP",
                            "LVX",
                            "CRO",
                            "CTX",
                            "CAZ",
                            "FEP",
                            "IPM",
                            "MEM",
                            "ETP",
                            "DOR",
                            "COL",
                        ],
                    },
                    {
                        PSEAER: [
                            "J01DD",
                            "J01GB",
                            "J01DH",
                            "J01XB",
                            "J01CR",
                            "CAZ",
                            "GEN",
                            "AMK",
                            "TOB",
                            "MEM",
                            "DOR",
                            "IPM",
                            "COL",
                            "TZP",
                        ],
                    },
                ],
                PHARYNGEAL: [
                    {
                        NEIGON: ["J01GB", "J01DD", "J01FA", "J01XX", "J01MA", "GEN", "CRO", "CFM", "AZM", "SPT", "CIP"],
                    },
                ],
                STOOL: [
                    {
                        SALSPP: [
                            "J01EE",
                            "J01MA",
                            "J01DD",
                            "J01DH",
                            "SXT",
                            "CIP",
                            "LVX",
                            "CRO",
                            "CAZ",
                            "CTX",
                            "IPM",
                            "MEM",
                            "ETP",
                            "DOR",
                        ],
                    },
                    {
                        SHISPP: ["J01EE", "J01MA", "J01DD", "J01FA", "SXT", "CIP", "LVX", "CRO", "CTX", "CAZ", "AZM"],
                    },
                ],
                URINE: [
                    {
                        ESCCOL: [
                            "J01XE",
                            "J01CA",
                            "J01EE",
                            "J01MA",
                            "J01DD",
                            "J01DE",
                            "J01DH",
                            "J01XB",
                            "NIT",
                            "MEC",
                            "SXT",
                            "CIP",
                            "LVX",
                            "CRO",
                            "CTX",
                            "CAZ",
                            "FEP",
                            "IPM",
                            "MEM",
                            "ETP",
                            "DOR",
                            "COL",
                        ],
                    },
                    {
                        KLEPNE: [
                            "J01CA",
                            "J01EE",
                            "J01MA",
                            "J01DD",
                            "J01DE",
                            "J01DH",
                            "J01XB",
                            "MEC",
                            "SXT",
                            "CIP",
                            "LVX",
                            "CRO",
                            "CTX",
                            "CAZ",
                            "FEP",
                            "IPM",
                            "MEM",
                            "ETP",
                            "DOR",
                            "COL",
                        ],
                    },
                ],
                UROGENITAL: [
                    {
                        NEIGON: ["J01GB", "J01DD", "J01FA", "J01XX", "J01MA", "GEN", "CRO", "CFM", "AZM", "SPT", "CIP"],
                    },
                ],
            },
        },
        dashboards: {
            reportsMenu: "",
            validationReport: "",
        },
        dataSubmissionPeriod: "YEARLY",
        dataColumns: [],
    },
    {
        id: AMC_MODULE_ID,
        name: "AMC",
        color: glassColors.lightTertiary,
        userGroups: {
            readAccess: [],
            captureAccess: [],
            approveAccess: [],
            confidentialAccess: [],
        },
        questionnaires: [],

        dashboards: {
            reportsMenu: "",
            validationReport: "",
        },
        dataSubmissionPeriod: "YEARLY",
        dataColumns: [],
    },
    {
        id: EGASP_MODULE_ID,
        name: "EGASP",
        color: glassColors.lightPrimary,
        userGroups: {
            readAccess: [],
            captureAccess: [],
            approveAccess: [],
            confidentialAccess: [],
        },
        questionnaires: [],
        dashboards: {
            reportsMenu: "",
            validationReport: "",
        },
        dataSubmissionPeriod: "YEARLY",
        dataColumns: [],
    },
];
