import { MODULE_NAMES } from "../entities/GlassModule";

const primaryFileTypes = ["RIS", "EGASP", "RIS Individual", "Product Level Data", "RIS Fungal"];
const secondaryFileTypes = ["SAMPLE", "SAMPLE File", "Substance Level Data"];

type PrimaryFileType = typeof primaryFileTypes[number];
type SecondaryFileType = typeof secondaryFileTypes[number];

export type ModuleDetails = {
    isbatchReq: boolean;
    isQuestionnaireReq: boolean;
    completeStatusChange: "QUESTIONNAIRE" | "DATASET" | "QUESTIONNAIRE_AND_DATASET";
    isSecondaryFileApplicable: boolean;
    isSecondaryRelated?: boolean;
    isDryRunReq: boolean;
    importLoadingMsg: {
        line1: string;
        line2: string;
    };
    deleteConfirmation: {
        title: string;
        description: string;
    };
    primaryFileType: PrimaryFileType;
    secondaryUploadLabel?: string;
    secondaryFileType: SecondaryFileType;
    primaryUploadLabel: string;
    unit: string;
    isSpecimenReq: boolean;
    isDownloadEmptyTemplateReq: boolean;
    applyQuestionnaireValidation: boolean;
    datasetString?: string;
    isDatasetMandatory: boolean;
    isSingleFileTypePerSubmission?: boolean; //For AMC, you can choose either product or substance file , never both
    autoGenerateDataSubmission: boolean;
    isCalculationRequired?: boolean;
    isDownloadDataAllowed?: boolean;
    downloadAllDataButtonReq?: boolean;
    isMultiDashboard?: boolean;
    isExternalSecondaryFile?: boolean; //For AMR-I, reuse AMR Aggregate Sample file metadata
    submittedDownloadLabel?: string;
    calculatedProductDownloadLabel?: string;
    calculatedSubstanceFileDownloadLabel?: string;
    hasAsyncDeletion?: boolean;
    hasAsyncUploads?: boolean;
    /** Refuse a primary file already imported (or queued) for the same period: re-importing it would duplicate records. */
    blockDuplicateUploads?: boolean;
};

export const moduleProperties = new Map<string, ModuleDetails>([
    [
        MODULE_NAMES.AMR,
        {
            isbatchReq: true,
            isQuestionnaireReq: true,
            completeStatusChange: "QUESTIONNAIRE",
            isSecondaryFileApplicable: true,
            isSecondaryRelated: true,
            isDryRunReq: true,
            importLoadingMsg: {
                line1: "Performing a dry run of the import to ensure that there are no errors.",
                line2: "This might take several minutes, do not refresh the page or press back.",
            },
            deleteConfirmation: {
                title: "Confirm Delete",
                description:
                    "Deleting this upload will delete both SAMPLE and RIS files for the given dataset. Are you sure you want to delete?",
            },
            primaryFileType: "RIS",
            secondaryFileType: "SAMPLE",
            primaryUploadLabel: "Choose RIS File",
            secondaryUploadLabel: "SAMPLE File,(not required)",
            unit: "data value",
            isSpecimenReq: true,
            isDownloadEmptyTemplateReq: false,
            applyQuestionnaireValidation: false,
            datasetString: "Upto 6 datasets",
            isDatasetMandatory: false,
            autoGenerateDataSubmission: true,
            hasAsyncDeletion: true,
        },
    ],
    [
        MODULE_NAMES.EGASP,
        {
            isbatchReq: false,
            isQuestionnaireReq: false,
            completeStatusChange: "DATASET",
            isSecondaryFileApplicable: false,
            isDryRunReq: false,
            importLoadingMsg: {
                line1: "Importing data,",
                line2: "This might take several minutes, do not refresh the page or press back.",
            },
            deleteConfirmation: {
                title: "Confirm Delete",
                description: "Are you sure you want to delete this EGASP file and corresponding events?",
            },
            primaryFileType: "EGASP",
            secondaryFileType: "",
            primaryUploadLabel: "Choose EGASP File",
            unit: "event",
            isSpecimenReq: false,
            isDownloadEmptyTemplateReq: true,
            applyQuestionnaireValidation: false,
            isDatasetMandatory: true,
            autoGenerateDataSubmission: true,
            downloadAllDataButtonReq: true,
            hasAsyncDeletion: true,
        },
    ],
    [
        MODULE_NAMES.AMR_INDIVIDUAL,
        {
            isbatchReq: false,
            isQuestionnaireReq: true,
            completeStatusChange: "QUESTIONNAIRE",
            isSecondaryFileApplicable: false,
            isDryRunReq: false,
            importLoadingMsg: {
                line1: "Importing data,",
                line2: "This might take several minutes, do not refresh the page or press back.",
            },
            deleteConfirmation: {
                title: "Confirm Delete",
                description: "Are you sure you want to delete this RIS individual file and corresponding enrollments?",
            },
            primaryFileType: "RIS Individual",
            secondaryFileType: "SAMPLE File",
            primaryUploadLabel: "Choose RIS Individual File",
            secondaryUploadLabel: "Choose SAMPLE File",
            unit: "enrollment",
            isSpecimenReq: true,
            isDownloadEmptyTemplateReq: false,
            applyQuestionnaireValidation: false,
            isDatasetMandatory: true,
            autoGenerateDataSubmission: true,
            downloadAllDataButtonReq: true,
            isExternalSecondaryFile: true,
            hasAsyncDeletion: true,
            hasAsyncUploads: true,
            blockDuplicateUploads: true,
        },
    ],
    [
        MODULE_NAMES.AMC,
        {
            isbatchReq: false,
            isQuestionnaireReq: true,
            completeStatusChange: "DATASET",
            isSecondaryFileApplicable: true,
            isDryRunReq: false,
            importLoadingMsg: {
                line1: "Importing data,",
                line2: "This might take several minutes, do not refresh the page or press back.",
            },
            deleteConfirmation: {
                title: "Confirm Delete",
                description: "Are you sure you want to delete this file",
            },
            primaryFileType: "Product Level Data",
            secondaryFileType: "Substance Level Data",
            primaryUploadLabel: "Choose File",
            secondaryUploadLabel: "Choose File",
            unit: "event",
            isSpecimenReq: false,
            isDownloadEmptyTemplateReq: true,
            applyQuestionnaireValidation: false,
            isSingleFileTypePerSubmission: true,
            isDatasetMandatory: true,
            autoGenerateDataSubmission: true,
            isCalculationRequired: true,
            isDownloadDataAllowed: true,
            submittedDownloadLabel: "Download submitted data",
            calculatedProductDownloadLabel: "Download calculated product data",
            calculatedSubstanceFileDownloadLabel: "Download calculated substance data",
            downloadAllDataButtonReq: true,
            isMultiDashboard: true,
            hasAsyncDeletion: true,
        },
    ],
    [
        MODULE_NAMES.AMR_FUNGAL,
        {
            isbatchReq: false,
            isQuestionnaireReq: true,
            completeStatusChange: "QUESTIONNAIRE",
            isSecondaryFileApplicable: false,
            isDryRunReq: false,
            importLoadingMsg: {
                line1: "Importing data,",
                line2: "This might take several minutes, do not refresh the page or press back.",
            },
            deleteConfirmation: {
                title: "Confirm Delete",
                description: "Are you sure you want to delete this RIS individual file and corresponding enrollments?",
            },
            primaryFileType: "RIS Fungal",
            secondaryFileType: "",
            primaryUploadLabel: "Choose RIS Fungal File",
            unit: "enrollment",
            isSpecimenReq: true,
            isDownloadEmptyTemplateReq: false,
            applyQuestionnaireValidation: false,
            isDatasetMandatory: true,
            autoGenerateDataSubmission: true,
            downloadAllDataButtonReq: true,
            hasAsyncDeletion: true,
            hasAsyncUploads: true,
            blockDuplicateUploads: true,
        },
    ],
]);

export function isPrimaryFileType(fileType: string): fileType is PrimaryFileType {
    return primaryFileTypes.includes(fileType as PrimaryFileType);
}
export function isSecondaryFileType(fileType: string): fileType is SecondaryFileType {
    return secondaryFileTypes.includes(fileType as SecondaryFileType);
}
